version: 2
updates
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
      devDependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
