/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarHeatmap: typeof import('./app/components/calendar-heatmap/index.vue')['default']
    Card: typeof import('./app/components/card/index.vue')['default']
    Footer: typeof import('./app/components/footer/index.vue')['default']
    Header: typeof import('./app/components/header/index.vue')['default']
    IconButton: typeof import('./app/components/icon-button/index.vue')['default']
    LinkToBack: typeof import('./app/components/link-to-back/index.vue')['default']
    LinkToEdit: typeof import('./app/components/link-to-edit/index.vue')['default']
    List: typeof import('./app/components/list/index.vue')['default']
    Modal: typeof import('./app/components/modal/index.vue')['default']
    NavigationMenu: typeof import('./app/components/navigation-menu/index.vue')['default']
    Pager: typeof import('./app/components/pager/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./app/components/search-input/index.vue')['default']
    ShareButton: typeof import('./app/components/share-button/index.vue')['default']
    SortMenu: typeof import('./app/components/sort-menu/index.vue')['default']
    Tag: typeof import('./app/components/tag/index.vue')['default']
    TagMenu: typeof import('./app/components/tag-menu/index.vue')['default']
    Toc: typeof import('./app/components/toc/index.vue')['default']
    Tooltip: typeof import('./app/components/tooltip/index.vue')['default']
    YearSelect: typeof import('./app/components/year-select/index.vue')['default']
  }
}
