/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarHeatmap: typeof import('./app/components/calendar-heatmap.vue')['default']
    Card: typeof import('./app/components/card.vue')['default']
    Footer: typeof import('./app/components/footer.vue')['default']
    Header: typeof import('./app/components/header.vue')['default']
    IconButton: typeof import('./app/components/icon-button.vue')['default']
    LinkButton: typeof import('./components/link-button.vue')['default']
    LinkToBack: typeof import('./app/components/link-to-back.vue')['default']
    LinkToEdit: typeof import('./app/components/link-to-edit.vue')['default']
    List: typeof import('./app/components/list.vue')['default']
    Modal: typeof import('./app/components/modal.vue')['default']
    NavigationMenu: typeof import('./app/components/navigation-menu.vue')['default']
    PageEditLink: typeof import('./components/page-edit-link.vue')['default']
    Pager: typeof import('./app/components/pager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./app/components/search-input.vue')['default']
    SortMenu: typeof import('./app/components/sort-menu.vue')['default']
    Tag: typeof import('./app/components/tag.vue')['default']
    Tooltip: typeof import('./app/components/tooltip.vue')['default']
    YearSelect: typeof import('./app/components/year-select.vue')['default']
  }
}
