name: Deploy chromatic

on:
  push:
    branches:
      - "**"

jobs:
  deploy-chromatic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clean temp directories
        run: |
          rm -rf /tmp/chromatic-*
          rm -rf ./.chromatic

      - name: Install dependencies
        run: npm install

      - name: Deploy chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          forceRebuild: true

      - name: Clean up
        if: always()
        run: |
          rm -rf /tmp/chromatic-*
          rm -rf ./.chromatic
          rm -rf ./*

      - name: Clear cache of npm
        if: always()
        run: npm cache clean --force
