name: Deploy chromatic

on:
  push:
    branches:
      - "**"

jobs:
  deploy-chromatic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Deploy chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Clean up
        run: |
          ls -la ./
          rm -rf ./*

      - name: Clear cache of npm
        run: npm cache clean --force
