name: Run vitest

on:
  push:
    branches:
      - "**"

jobs:
  run-vitest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run vitest
        run: npm run vitest

      - name: Clean up
        run: |
          ls -la ./
          rm -rf ./*

      - name: Clear cache of npm
        run: npm cache clean --force
