name: Run vitest

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  run-vitest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      WORKING_DIRECTORY: app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run vitest
        run: npm run test:unit
      - name: Show coverage report
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
